# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f5989002a9aff5e6564704dadd56daefc2b74344e376167eb325594ae23689000b7399630f010498015098f0badfa1e65a42760b302fec4663bb5b4de7c808

test:
  secret_key_base: cbb5499b6eb2765578908627bd9ebfe52347909358ad6baaea26e94418d085dff5cc58be79d26c9a79844d6276c23e03fa3fca0193fd7b6dc05e86fae2dd9779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
